### PR TITLE
[PG-172]: add 'simpler' aggregate trait

### LINKED ISSUE #68: Aggregate state is modified by `do_handle_command`
# Problem
do handle command has the signature:
```rust
async fn do_handle_command(
    &self,
    aggregate_state: AggregateState<Self::State>,
    cmd: Self::Command,
) -> Result<AggregateState<Self::State>, Self::Error>;
```

as a result, in order to persist an event, `&self.persist` is called during `do_handle_command` - which means that `do_handle_command` is responsible for threading the aggregate state through to `persist`, which then internally makes a call to `apply_event`.

This means that `do_handle_command` can arbitrarily change the value of the `AggregateState` before passing it through to persist, e.g:
```rust
    async fn do_handle_command(
        &self,
        aggregate_state: AggregateState<Self::State>,
        cmd: Self::Command,
    ) -> Result<AggregateState<Self::State>, Self::Error> {
        match cmd {
            QuoteCommand::Create(payload) => {
                self.persist(
                    AggregateState::new_with_state(Uuid::new_v4(), {}),
                    QuoteEvent::Created(payload.into()),
                )
                .await
            }
        }
    }
```

This means that the aggregate state could be set to a value that *would not be recreated* by the `load` function.

# Possible solutions:
we could rename the `Aggregate` trait to `AggregateManager` (or equivalent) and then have a separate *sync* `Aggregate` trait:
```rust
pub trait Aggregate: Identifier {
    type State: Default + Debug + Clone + Send + Sync;
    type Command: Send + Sync;
    type Event: Serialize + DeserializeOwned + Clone + Send + Sync;
    type Error: Send + Sync;

    /// This function applies the event onto the aggregate and returns a new one, updated with the event data
    fn apply_event(id: &Uuid, state: Self::State, event: &Self::Event) -> Self::State;

    fn validate_command(aggregate_state: &AggregateState<Self::State>, cmd: &Self::Command) -> Result<(), Self::Error>;

    fn handle_command(
        &self,
        aggregate_state: AggregateState<Self::State>,
        cmd: Self::Command,
    ) -> Result<Self::Event, Self::Error>;
}
```

so `AggregateManager` would be responsible for calling `self.aggregate.validate`, `self.aggregate.handle_command`, `self.persist`, `self.aggregate.apply_event` in order, but then the pipeline would not be overrideable/broken by implementors of `Aggregate`

### PR DESCRIPTION
**Pull request by emturner**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PG-172

closes #68

Renames `Aggregate` to `AggregateManager` and introduces a new, simplified `Aggregate` trait.  The aim is to reduce the implementation complexity of aggregates for the majority of use-cases (ie _pure aggregates_).

There is a default implementation of `AggregateManager` for `Aggregate` - so that implementors of the `Aggregate` trait get the correct 'pipelining' behaviour for free.

demo tracking branch of [platform-global](https://github.com/primait/platform-global/pull/86)

#69 is in progress - but was getting rather large so wanted to split this out first

### CODE REVIEW

File: examples/postgres_payments/src/credit_card/aggregate.rs [hunk 1]
```diff
@@ -58,8 +55,8 @@ impl Aggregate for CreditCardAggregate {
     }
 
     // No state for credit_card aggregate
-    fn apply_event(_id: &Uuid, state: CreditCardState, event: &StoreEvent<Self::Event>) -> CreditCardState {
-        match event.payload() {
+    fn apply_event(state: CreditCardState, event: &Self::Event) -> CreditCardState {
```
Comment (cottinisimone) [inline examples/postgres_payments/src/credit_card/aggregate.rs:58]: I left the event wrapped inside the StoreEvent because I thought that maybe one of the inner field could have been useful for the state. Eg. assumptions over sequence_number or occurred_on. WDYT?

**Review by cottinisimone — COMMENTED** [review]
Thank you for this PR and for the documentation you added

File: examples/postgres_payments/src/credit_card/aggregate.rs (hunk 1 above)
Comment (emturner) [reply examples/postgres_payments/src/credit_card/aggregate.rs:58]: I think that it makes sense for `projectors` etc to take the `StoreEvent` - since any metadata currently lives there.  (separately - I guess it could be worth thinking about how we handle metadata/tracing properly? (e.g. how pass through `correlation_id` through the system)

but it feels a bit odd to me for the core aggregate to have access to things like `occured_on`/`sequence_number` - depending on `sequence_number` in the state feels a bit flaky.  And as with `occured_on`, if the aggregate needs a sequence or a timestamp then potentially they should be placed in the commands/events explicitly?

File: src/esrs/aggregate.rs [hunk 2]
```diff
@@ -113,3 +134,73 @@ pub trait Aggregate: Identifier {
             })?)
     }
 }
+
+/// The Aggregate trait is responsible for validating commands, mapping commands to events, and
+/// mapping commands to events.
```
Comment (matteosister) [inline src/esrs/aggregate.rs:139]: ...and mapping commands to events :smile:

**Review by matteosister — APPROVED** [review]
great!

File: src/esrs/aggregate.rs (hunk 2 above)
Comment (emturner) [reply src/esrs/aggregate.rs:139]: the `and` is on the previous line 😀
